# Generated by Django 6.0.3 on 2026-06-02 23:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=100, unique=True)),
                ('core_question', models.TextField()),
                ('current_frame', models.JSONField(default=dict)),
                ('state_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(default='fa-globe', max_length=100)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='NOT_STARTED', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='discovery.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='ExplorationBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_made', models.CharField(max_length=255)),
                ('branch_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorations', to='discovery.inquiry')),
                ('parent_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offshoots', to='discovery.planet')),
            ],
        ),
    ]
