# Generated by Django 6.0.3 on 2026-06-03 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='assumptions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='confidence_evolution',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='constraints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='current_question_state',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='evidence_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='history_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='hypothesis_set',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='solution_families',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='unresolved_zones',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='explorationbranch',
            name='parent_planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offshoots', to='discovery.planet'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='case_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='EngineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_timestamp', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(max_length=255)),
                ('result_snapshot', models.JSONField()),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_runs', to='discovery.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('DISCOVERY', 'Discovery Room'), ('EVIDENCE', 'Evidence Room'), ('EXPLORATION', 'Exploration Room'), ('SOLUTION', 'Solution Room'), ('PROJECTION', 'Projection Room'), ('GOVERNANCE', 'Governance Room'), ('UNCERTAINTY', 'Uncertainty Room'), ('DECISION', 'Decision Room')], max_length=20)),
                ('room_data', models.JSONField(default=dict)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_states', to='discovery.inquiry')),
            ],
        ),
    ]
