# Generated by Django 6.0.3 on 2026-06-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_inquiry_assumptions_inquiry_confidence_evolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_model', models.CharField(choices=[('gpt-4o', 'GPT-4o (High Accuracy)'), ('claude-3-5-sonnet', 'Claude 3.5 Sonnet (High Reasoning)'), ('gpt-4-turbo', 'GPT-4 Turbo')], default='claude-3-5-sonnet', max_length=50)),
                ('reasoning_depth', models.IntegerField(default=7, help_text='Depth of Step 6 propagation')),
                ('enable_web_search', models.BooleanField(default=True)),
                ('strict_governance', models.BooleanField(default=True, help_text='Bypass Step 10 if Step 9 fails')),
                ('linear_ui_mode', models.BooleanField(default=True)),
                ('auto_refresh_ms', models.IntegerField(default=5000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
