# Generated by Django 6.0.3 on 2026-06-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='offline_mode',
            field=models.BooleanField(default=False, help_text='Simulate reasoning without API calls'),
        ),
    ]
