# Generated by Django 6.0.3 on 2026-06-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_systemsettings_offline_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='API Key for Claude models', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='API Key for GPT models', max_length=255, null=True),
        ),
    ]
