# Generated by Django 6.0.3 on 2026-06-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_alter_systemsettings_active_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='active_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (High Accuracy)'), ('claude-sonnet-4-6', 'Claude Sonnet (High Reasoning)'), ('gpt-4-turbo', 'GPT-4 Turbo')], default='claude-sonnet-4-6', max_length=50),
        ),
    ]
