# Generated by Django 6.0.3 on 2026-06-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_alter_systemsettings_active_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='unresolved_zones',
            new_name='uncertainty_zones',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='evidence_map',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='hypothesis_set',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='governance_events',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='transformations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='roomstate',
            name='room_type',
            field=models.CharField(choices=[('DISCOVERY', 'Discovery Room'), ('EVIDENCE', 'Evidence Room'), ('SYSTEMS', 'Systems / Landscape Room'), ('GOVERNANCE', 'Governance Room'), ('PROJECTION', 'Projection Room')], max_length=20),
        ),
    ]
