# Generated by Django 6.0.3 on 2026-06-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_rename_unresolved_zones_inquiry_uncertainty_zones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='governance_events',
            new_name='unresolved_zones',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='transformations',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='uncertainty_zones',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='evidence_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='hypothesis_set',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='roomstate',
            name='room_type',
            field=models.CharField(choices=[('DISCOVERY', 'Discovery Room'), ('EVIDENCE', 'Evidence Room'), ('EXPLORATION', 'Exploration Room'), ('SOLUTION', 'Solution Room'), ('PROJECTION', 'Projection Room'), ('GOVERNANCE', 'Governance Room'), ('UNCERTAINTY', 'Uncertainty Room'), ('DECISION', 'Decision Room')], max_length=20),
        ),
    ]
