# Generated by Django 6.0.3 on 2026-06-03 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_rename_governance_events_inquiry_unresolved_zones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='assumptions',
            field=models.JSONField(default=list, help_text='Load-bearing assumptions surfaced by Step 3.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='case_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='core_question',
            field=models.TextField(help_text='The original input frame.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='current_question_state',
            field=models.TextField(blank=True, help_text='The evolved inquiry state.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='history_log',
            field=models.JSONField(default=list, help_text='Traceable audit of all cognitive mutations.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='hypothesis_set',
            field=models.JSONField(default=dict, help_text='Active and falsified possibilities.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='solution_families',
            field=models.JSONField(default=list, help_text='Competing solution architectures (Pluralism).'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='unresolved_zones',
            field=models.JSONField(default=list, help_text='Residual Darkness / Regulatory uncertainty (The One).'),
        ),
    ]
