# Generated by Django 6.0.3 on 2026-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0010_alter_inquiry_assumptions_alter_inquiry_case_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='active_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (High Accuracy)'), ('claude-3-5-sonnet-20240620', 'Claude 3.5 Sonnet (High Reasoning)'), ('gpt-4-turbo', 'GPT-4 Turbo')], default='claude-3-5-sonnet-20240620', max_length=50),
        ),
    ]
