# Generated by Django 6.0.3 on 2026-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0011_alter_systemsettings_active_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='API Key for Google Gemini models', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='active_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o (High Accuracy)'), ('claude-3-5-sonnet-20240620', 'Claude 3.5 Sonnet (High Reasoning)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Fast/Free)'), ('gpt-4-turbo', 'GPT-4 Turbo')], default='claude-3-5-sonnet-20240620', max_length=50),
        ),
    ]
