# Generated by Django 6.0.3 on 2026-06-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0013_alter_systemsettings_active_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='gemini_api_key',
        ),
    ]
