# Generated by Django 6.0.3 on 2026-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0015_systemsettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='active_model',
            field=models.CharField(choices=[('claude-3-5-sonnet-20240620', 'Claude 3.5 Sonnet'), ('gemini-1.5-flash-latest', 'Gemini 1.5 Flash')], default='claude-3-5-sonnet-20240620', max_length=50),
        ),
    ]
