# Generated by Django 6.0.3 on 2026-06-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0017_alter_systemsettings_active_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='openai_api_key',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='active_model',
            field=models.CharField(choices=[('sonnet', 'Claude 3.5 Sonnet (Canonical)')], default='sonnet', max_length=50),
        ),
        migrations.CreateModel(
            name='SpendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(help_text='The ELIF reasoning step (e.g. Frame Validator)', max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spend_records', to='discovery.inquiry')),
            ],
        ),
    ]
