# Generated by Django 6.0.3 on 2026-06-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0018_remove_systemsettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='branch_name',
            field=models.CharField(blank=True, help_text='The name of the trajectory this branch represents.', max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='divergences',
            field=models.JSONField(default=list, help_text='First-class inquiry forks / competing futures.'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='parent_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='discovery.inquiry'),
        ),
    ]
