# Generated by Django 6.0.3 on 2026-06-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0019_inquiry_branch_name_inquiry_divergences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendrecord',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_records', to='discovery.inquiry'),
        ),
    ]
