# Generated by Django 6.0.3 on 2026-06-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0020_alter_spendrecord_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='current_status_msg',
            field=models.CharField(blank=True, default='Initializing Engine...', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='debug_mode',
            field=models.BooleanField(default=False, help_text='Expose engine telemetry during execution'),
        ),
    ]
