# Generated by Django 6.0.3 on 2026-06-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0021_inquiry_current_status_msg_systemsettings_debug_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='topic',
            field=models.CharField(default='General', help_text='The thematic folder/category for this inquiry.', max_length=255),
        ),
    ]
