# Generated by Django 6.0.5 on 2026-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0022_inquiry_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='final_verdict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUSED', 'Refused')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='planet',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
    ]
