# Generated by Django 6.0.5 on 2026-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0023_inquiry_final_verdict_inquiry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='stability_evolution',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='roomstate',
            name='room_type',
            field=models.CharField(choices=[('DISCOVERY', 'Discovery Room'), ('PROCESS', 'Process Room'), ('EVIDENCE', 'Evidence Room'), ('EXPLORATION', 'Exploration Room'), ('SOLUTION', 'Solution Room'), ('PROJECTION', 'Projection Room'), ('GOVERNANCE', 'Governance Room'), ('UNCERTAINTY', 'Uncertainty Room'), ('DECISION', 'Decision Room')], max_length=20),
        ),
    ]
