# Generated by Django 6.0.5 on 2026-06-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0024_inquiry_stability_evolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='investigation_status',
            field=models.CharField(default='Emerging', help_text='The qualitative status of the inquiry (e.g., Emerging, Validated).', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomstate',
            name='room_type',
            field=models.CharField(choices=[('DISCOVERY', 'Discovery Room'), ('EVIDENCE', 'Evidence Room'), ('EXPLORATION', 'Exploration Room'), ('SOLUTION', 'Solution Room'), ('PROJECTION', 'Projection Room'), ('GOVERNANCE', 'Governance Room'), ('UNCERTAINTY', 'Uncertainty Room'), ('DECISION', 'Decision Room')], max_length=20),
        ),
    ]
