# Generated by Django 6.0.5 on 2026-06-05 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0026_inquiry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inquiry_limit', models.IntegerField(default=5, help_text='Maximum number of inquiries allowed.')),
                ('spend_limit', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum USD spend allowed.', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price for this tier.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='discovery.tier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
