# Generated by Django 6.0.5 on 2026-06-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0027_tier_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_tier',
            field=models.ForeignKey(blank=True, help_text='Automatically assigned to new users.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='discovery.tier'),
        ),
    ]
