# Generated by Django 6.0.5 on 2026-06-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0030_spendrecord_case_id_snapshot_spendrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='total_inquiries_consumed',
            field=models.IntegerField(default=0, help_text='Lifetime inquiries started, non-decrementing.'),
        ),
    ]
