# Generated by Django 6.0.5 on 2026-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0031_usersubscription_total_inquiries_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='show_spending_overview',
            field=models.BooleanField(default=True, help_text='Show or hide USD accumulation metrics for users.'),
        ),
    ]
