# Generated by Django 6.0.5 on 2026-06-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0032_systemsettings_show_spending_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_visible_to_user',
            field=models.BooleanField(default=True, help_text="Set to False when a user 'deletes' the inquiry to persist it for admin audit."),
        ),
    ]
