# Generated by Django 6.0.5 on 2026-06-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0033_inquiry_is_visible_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='system_version',
            field=models.CharField(default='V1.0 ALPHA', help_text='Version string displayed in sidebar', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUSED', 'Refused'), ('DELETED', 'Deleted')], default='PENDING', max_length=20),
        ),
    ]
