# Generated by Django 6.0.5 on 2026-06-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0034_systemsettings_system_version_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='documentation_content',
            field=models.TextField(default='# ELIF Protocol Documentation\n\nWelcome to the official ELIF documentation. This guide details the cognitive engine architecture, hypothesis validation layers, and operative truth separates protocols.', help_text='Markdown content for the Documentation page.'),
        ),
    ]
