# Generated by Django 6.0.5 on 2026-06-05 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0035_systemsettings_documentation_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tester_free_inquiry_limit',
            field=models.IntegerField(default=10, help_text='Inquiries available for Testers before survey/cutoff.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tester_survey_schema',
            field=models.JSONField(default=list, help_text='List of questions for the tester survey.'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=dict, help_text="Configured by Superuser for 'Limited Admin' type."),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='has_completed_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user_type',
            field=models.CharField(choices=[('NORMAL', 'Normal User'), ('ADMIN', 'Limited Admin'), ('TESTER', 'Beta Tester')], default='NORMAL', max_length=20),
        ),
        migrations.CreateModel(
            name='TesterSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
