# Generated by Django 6.0.5 on 2026-06-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0036_systemsettings_tester_free_inquiry_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tester_free_spend_limit',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='USD spend available for Testers before cutoff.', max_digits=10),
        ),
    ]
