# Generated by Django 6.0.5 on 2026-06-06 01:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0037_systemsettings_tester_free_spend_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='billing_start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='monthly_inquiries_consumed',
            field=models.IntegerField(default=0, help_text='Inquiries consumed in current billing cycle.'),
        ),
    ]
