# Generated by Django 6.0.5 on 2026-06-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0038_usersubscription_billing_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('YES_NO', 'Yes / No'), ('MCQ', 'Multiple Choice'), ('FREE', 'Free Text Answer')], max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for MCQ type.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='testersurveyresponse',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Reason for re-ask request.', null=True),
        ),
        migrations.AddField(
            model_name='testersurveyresponse',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='If true, tester must re-answer.'),
        ),
    ]
