# Generated by Django 6.0.5 on 2026-06-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0039_testerquestion_testersurveyresponse_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='monthly_spend_consumed',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Spend consumed in current billing cycle.', max_digits=10),
        ),
    ]
