# Generated by Django 6.0.5 on 2026-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0042_usersubscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='specialization',
            field=models.CharField(blank=True, help_text="User's expertise specialization for this inquiry.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='research_specializations',
            field=models.JSONField(blank=True, default=list, help_text='User-defined areas of expertise.'),
        ),
    ]
