# Generated by Django 6.0.5 on 2026-06-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0043_remove_usersubscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='has_seen_walkthrough',
            field=models.BooleanField(default=False),
        ),
    ]
