# Generated by Django 6.0.5 on 2026-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0044_usersubscription_has_seen_walkthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Mark this tier as 'Recommended' on the landing page."),
        ),
    ]
