# Generated by Django 6.0.5 on 2026-06-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0045_tier_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='API Key for DeepSeek models', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='active_model',
            field=models.CharField(choices=[('deepseek-chat', 'DeepSeek Chat (Standard)'), ('deepseek-reasoner', 'DeepSeek Reasoner (R1)'), ('sonnet', 'Claude 3.5 Sonnet (Legacy)')], default='deepseek-chat', max_length=50),
        ),
    ]
