# Generated by Django 6.0.5 on 2026-06-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0046_systemsettings_deepseek_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='active_model',
            field=models.CharField(choices=[('deepseek-chat', 'DeepSeek Chat (Standard)'), ('deepseek-reasoner', 'DeepSeek Reasoner (R1)'), ('sonnet', 'Claude 4.5 Sonnet (Canonical)')], default='deepseek-chat', max_length=50),
        ),
    ]
