# Generated by Django 6.0.5 on 2026-06-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0047_systemsettings_stripe_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='stripe_live_mode',
            field=models.BooleanField(default=False, help_text='If True, uses Stripe Production. If False, uses Test Mode.'),
        ),
        migrations.AddField(
            model_name='tier',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_status',
            field=models.CharField(blank=True, help_text='e.g. active, past_due, canceled', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
