# Generated by Django 6.0.5 on 2026-06-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0048_stripewebhooklog_systemsettings_stripe_live_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='db_pg_host',
            field=models.CharField(blank=True, default='localhost', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='db_pg_name',
            field=models.CharField(blank=True, help_text='Database Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='db_pg_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='db_pg_port',
            field=models.CharField(blank=True, default='5432', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='db_pg_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='use_postgres',
            field=models.BooleanField(default=False, help_text='Enable Postgres backend (requires server configuration)'),
        ),
    ]
