# Generated by Django 6.0.5 on 2026-06-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0049_systemsettings_db_pg_host_systemsettings_db_pg_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='db_error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='db_last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='db_last_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='db_pg_ssl_mode',
            field=models.CharField(choices=[('disable', 'disable'), ('allow', 'allow'), ('prefer', 'prefer'), ('require', 'require'), ('verify-ca', 'verify-ca'), ('verify-full', 'verify-full')], default='prefer', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='db_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
