# Generated by Django 6.0.5 on 2026-06-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0050_systemsettings_db_error_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='db_pg_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='db_pg_port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
