# Generated by Django 6.0.5 on 2026-06-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0051_alter_systemsettings_db_pg_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='db_version',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='use_postgres',
            field=models.BooleanField(default=True, help_text='Enable Postgres backend (requires server configuration)'),
        ),
    ]
