# Generated by Django 6.0.3 on 2026-06-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0053_businessalert_dailyfinancialsnapshot_platformcost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesterQuestion',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='tester_free_inquiry_limit',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='tester_free_spend_limit',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='tester_survey_schema',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='has_completed_survey',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user_type',
            field=models.CharField(choices=[('NORMAL', 'Normal User'), ('ADMIN', 'Limited Admin')], default='NORMAL', max_length=20),
        ),
        migrations.DeleteModel(
            name='TesterSurveyResponse',
        ),
    ]
