# Generated by Django 6.0.3 on 2026-06-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0055_systemsettings_email_from_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CORE', 'Core System'), ('ENGINE', 'Reasoning Engine'), ('AI', 'AI Provider'), ('DATABASE', 'Database Integrity'), ('PAYMENT', 'Payment System'), ('SECURITY', 'Security & Access'), ('INFRA', 'Infrastructure'), ('API', 'External APIs'), ('UX', 'Frontend & UX'), ('FINANCE', 'Financial Reliability'), ('CHAOS', 'Chaos Mode')], max_length=50)),
                ('test_type', models.CharField(default='STANDARD', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('health_score', models.IntegerField(default=0)),
                ('results', models.JSONField(default=dict)),
                ('logs', models.TextField(blank=True)),
                ('execution_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user_type',
            field=models.CharField(choices=[('NORMAL', 'Normal User'), ('ADMIN', 'Limited Admin')], default='NORMAL', max_length=20),
        ),
    ]
