# Generated by Django 6.0.5 on 2026-06-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0056_systemtestrun_alter_usersubscription_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admin_alert_email',
            field=models.EmailField(blank=True, help_text='Where to send high-priority system alerts.', max_length=254, null=True),
        ),
    ]
