# Generated by Django 6.0.3 on 2026-06-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0057_systemsettings_admin_alert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='hero_stat_automations',
            field=models.CharField(default='200M+', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hero_stat_rating',
            field=models.CharField(default='4.9/5', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hero_stat_uptime',
            field=models.CharField(default='99.9%', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hero_stat_users',
            field=models.CharField(default='50K+', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='integrations_data',
            field=models.JSONField(default=list, help_text='List of {name, icon, description, status}'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_faq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_hero_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_integrations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_pricing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_testimonials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='testimonials_data',
            field=models.JSONField(default=list, help_text='List of {name, role, quote}'),
        ),
    ]
