# Generated by Django 6.0.3 on 2026-06-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0058_systemsettings_hero_stat_automations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='hero_stat_automations',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='hero_stat_rating',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='hero_stat_uptime',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='hero_stat_users',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='integrations_data',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='show_faq',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='show_hero_stats',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='show_integrations',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='show_pricing',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='show_testimonials',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='testimonials_data',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='stat_active_users',
            field=models.CharField(default='50K+', help_text='Active Users count displayed on landing', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='stat_automations_run',
            field=models.CharField(default='200M+', help_text='Automations Run count displayed on landing', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='stat_avg_rating',
            field=models.CharField(default='4.9/5', help_text='Average Rating displayed on landing', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='stat_uptime',
            field=models.CharField(default='99.9%', help_text='Uptime percentage displayed on landing', max_length=20),
        ),
    ]
