# Generated by Django 6.0.3 on 2026-06-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0059_remove_systemsettings_hero_stat_automations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='External URL for favicon', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External URL for sidebar/landing logo', max_length=1024, null=True),
        ),
    ]
