# Generated by Django 6.0.3 on 2026-06-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0060_systemsettings_favicon_url_systemsettings_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='yearly_discount_percent',
            field=models.IntegerField(default=40, help_text='Discount percentage shown for yearly plans (e.g. 40)'),
        ),
    ]
