# Generated by Django 6.0.3 on 2026-06-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0061_systemsettings_yearly_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total yearly price for this tier.', max_digits=10),
        ),
    ]
