# Generated by Django 6.0.3 on 2026-06-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0062_tier_price_yearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='is_contact_only',
            field=models.BooleanField(default=False, help_text="If True, price is hidden and replaced with 'Contact Us'."),
        ),
    ]
