from django.urls import path
from . import views

app_name = 'discovery'

urlpatterns = [
    path('', views.landing_page, name='landing'),
    path('dashboard/', views.system_map, name='system_map'),
    path('initialize/', views.initialize_inquiry, name='initialize'),
    path('inquiry/<pk>/', views.inquiry_detail, name='inquiry_detail'),
    path('inquiry/<pk>/room/<str:room_type>/', views.room_view, name='room_view'),
    path('inquiry/<pk>/sync/', views.sync_engine_pulse, name='sync_engine'),
    path('inquiry/<pk>/branch/', views.spawn_branch_view, name='spawn_branch'),
    path('inquiry/<pk>/refine/', views.refine_inquiry, name='refine_inquiry'),
    path('inquiry/<pk>/reset/', views.reset_inquiry, name='reset'),
    path('inquiry/<pk>/delete/', views.delete_inquiry, name='delete'),
    path('inquiry/<pk>/telemetry/', views.engine_telemetry, name='telemetry'),
    path('inquiry/<pk>/events/', views.engine_events, name='engine_events'),
    path('profile/', views.profile_view, name='profile'),
    path('sovereign/settings/', views.system_settings_view, name='settings'),
    path('settings/clear-lock/', views.clear_engine_lock, name='clear_lock'),
    path('spend/', views.spend_history, name='spend_history'), path('analytics/', views.analytics_dashboard, name='analytics'),
    path('subscription/', views.subscription_view, name='subscription'),
    path('documentation/', views.documentation_view, name='documentation'),
    path('tester-survey/', views.tester_survey, name='tester_survey'),
    path('tester-feedback/', views.tester_feedback_center, name='tester_feedback_center'),
    path('topic/<str:topic_name>/', views.topic_detail, name='topic_detail'),
    path('task/<str:task_id>/status/', views.task_status_view, name='task_status'),
    path('signup/', views.signup, name='signup'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/tiers/', views.tier_list, name='tier_list'),
    path('admin-dashboard/tiers/limits/', views.admin_limits_config, name='admin_limits_config'),
    path('admin-dashboard/tiers/add/', views.tier_upsert, name='tier_add'),
    path('admin-dashboard/tiers/<int:pk>/edit/', views.tier_upsert, name='tier_edit'),
    path('admin-dashboard/tiers/<int:pk>/delete/', views.tier_delete, name='tier_delete'),
    path('admin-dashboard/users/', views.users_list, name='users_list'),
    path('admin-dashboard/users/<int:user_id>/', views.user_detail, name='user_detail'),
    path('admin-dashboard/users/<int:user_id>/toggle/', views.toggle_user_status, name='toggle_user'),
    path('admin-dashboard/users/<int:user_id>/reset-usage/', views.manual_reset_usage, name='reset_usage'),
    path('admin-dashboard/heal/', views.admin_heal_engine, name='admin_heal'),
    path('admin-dashboard/inquiry/<pk>/status/', views.update_inquiry_status, name='update_inquiry_status'),
    path('report-issue/', views.report_issue, name='report_issue'),
    path('my-issues/', views.user_issues, name='user_issues'),
    path('admin-dashboard/issues/', views.admin_issue_center, name='admin_issue_center'),
    path('admin-dashboard/issues/<int:issue_id>/update/', views.update_issue_status, name='update_issue'),
    path('admin-dashboard/intelligence/', views.admin_intelligence_hub, name='admin_intelligence_hub'),
    path('admin-dashboard/intelligence/questions/', views.manage_tester_questions, name='manage_tester_questions'),
    path('admin-dashboard/intelligence/reask/<int:response_id>/', views.reask_tester_feedback, name='reask_tester_feedback'),
    path('inquiry/<pk>/export/<str:format>/', views.export_inquiry, name='export_inquiry'),
    path('notifications/', views.get_notifications, name='get_notifications'),
    path('notifications/clear-all/', views.clear_all_notifications, name='clear_all_notifications'),
    path('notifications/<int:pk>/read/', views.mark_notification_read, name='mark_read'),
    path('walkthrough/complete/', views.complete_walkthrough, name='complete_walkthrough'),
]

