"""
Django settings for elif_platform project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add the engine src directory to path
ENGINE_SRC = BASE_DIR.parent / "src"
sys.path.append(str(ENGINE_SRC))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@d+^bhenx!p((h#kb4l4s7c--n)zxrn5d8-*b4(@=mc08%vqh='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# ELIF Alpha Engine Keys
ELIF_ANTHROPIC_API_KEY = os.getenv('ELIF_ANTHROPIC_API_KEY', '')
# Only set os.environ if the key is present
if ELIF_ANTHROPIC_API_KEY:
    os.environ["ELIF_ANTHROPIC_API_KEY"] = ELIF_ANTHROPIC_API_KEY

# Serverless Engine Configuration
# Set to None for local execution, or URL of deployed Cloud Function
ELIF_ENGINE_URL = os.getenv('ELIF_ENGINE_URL', 'http://127.0.0.1:8080')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'discovery',
    'engine_bridge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'elif_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'discovery.context_processors.system_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'elif_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'

# Celery Settings
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')

# --- SERVERLESS / DISTRIBUTED CONFIG ---
# If False, tasks are sent to Redis and handled by separate elastically scaling workers.
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
# ----------------------------------------

# --- PRODUCTION SCALABILITY & PROTECTION ---
CELERY_WORKER_CONCURRENCY = 4      # Limit parallel engine steps
CELERY_TASK_ACKS_LATE = True       # Re-run tasks if worker dies
CELERY_WORKER_PREFETCH_MULTIPLIER = 1 # Fair distribution for long tasks
CELERY_TASK_SOFT_TIME_LIMIT = 500  # 8.3 mins per step
CELERY_TASK_TIME_LIMIT = 600       # 10 mins hard limit

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
LOGOUT_REDIRECT_URL = '/'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Media Files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
