"""
Django settings for elif_platform project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
import json
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add the engine src directory to path
ENGINE_SRC = BASE_DIR.parent / "src"
sys.path.append(str(ENGINE_SRC))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-@d+^bhenx!p((h#kb4l4s7c--n)zxrn5d8-*b4(@=mc08%vqh=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", ""
).split(",")

# ELIF Alpha Engine Keys
ELIF_ANTHROPIC_API_KEY = os.getenv('ELIF_ANTHROPIC_API_KEY', '')
# Only set os.environ if the key is present
if ELIF_ANTHROPIC_API_KEY:
    os.environ["ELIF_ANTHROPIC_API_KEY"] = ELIF_ANTHROPIC_API_KEY

# Serverless Engine Configuration
# Set to None/Empty for local execution, or URL of deployed Cloud Function
ELIF_ENGINE_URL = os.getenv('ELIF_ENGINE_URL', '')

# Engine Case Discovery
ELIF_CASES_DIR = os.getenv('ELIF_CASES_DIR', str(BASE_DIR.parent / "cases"))
os.environ["ELIF_CASES_DIR"] = ELIF_CASES_DIR


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'discovery',
    'engine_bridge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'elif_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'discovery.context_processors.system_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'elif_platform.wsgi.application'


# --- DATABASE CONFIGURATION ---
# Default credentials (Aiven Production)
POSTGRES_CONFIG = {
    'NAME': os.getenv('DB_NAME', 'defaultdb'),
    'USER': os.getenv('DB_USER', 'avnadmin'),
    'PASSWORD': os.getenv('DB_PASSWORD', ''),
    'HOST': os.getenv('DB_HOST', 'elif-rabahdjebbes6-11c6.i.aivencloud.com'),
    'PORT': os.getenv('DB_PORT', '22943'),
    'SSL_MODE': os.getenv('DB_SSL_MODE', 'prefer'),
}
USE_POSTGRES = os.getenv('USE_POSTGRES', 'True').lower() == 'true'

# Load persistent mirror to allow UI-based overrides and survival across migrations
DB_CONFIG_PATH = BASE_DIR / 'db_config.json'
if DB_CONFIG_PATH.exists():
    try:
        with open(DB_CONFIG_PATH, 'r') as f:
            DC = json.load(f)
            USE_POSTGRES = DC.get('use_postgres', True)
            
            # If UI has customized the database, override defaults
            if DC.get('db_pg_host'):
                POSTGRES_CONFIG['HOST'] = DC['db_pg_host']
                POSTGRES_CONFIG['PORT'] = DC.get('db_pg_port', POSTGRES_CONFIG['PORT'])
                POSTGRES_CONFIG['NAME'] = DC.get('db_pg_name', POSTGRES_CONFIG['NAME'])
                POSTGRES_CONFIG['USER'] = DC.get('db_pg_user', POSTGRES_CONFIG['USER'])
                POSTGRES_CONFIG['PASSWORD'] = DC.get('db_pg_password', POSTGRES_CONFIG['PASSWORD'])
                POSTGRES_CONFIG['SSL_MODE'] = DC.get('db_pg_ssl_mode', POSTGRES_CONFIG['SSL_MODE'])
    except Exception:
        pass
# -----------------------------

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql' if USE_POSTGRES else 'django.db.backends.sqlite3',
        'NAME': POSTGRES_CONFIG['NAME'] if USE_POSTGRES else BASE_DIR / 'db.sqlite3',
        'USER': POSTGRES_CONFIG['USER'] if USE_POSTGRES else '',
        'PASSWORD': POSTGRES_CONFIG['PASSWORD'] if USE_POSTGRES else '',
        'HOST': POSTGRES_CONFIG['HOST'] if USE_POSTGRES else '',
        'PORT': POSTGRES_CONFIG['PORT'] if USE_POSTGRES else '',
        'OPTIONS': {
            'sslmode': POSTGRES_CONFIG['SSL_MODE'],
            'connect_timeout': 60,
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        } if USE_POSTGRES else {},
    },
    'sqlite_source': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'discovery:system_map'

# Celery Settings
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', os.getenv('REDIS_URL', 'redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)

# --- SERVERLESS / DISTRIBUTED CONFIG ---
# If False, tasks are sent to Redis and handled by separate elastically scaling workers.
CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_TASK_ALWAYS_EAGER', 'True').lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True
# ----------------------------------------

# --- PRODUCTION SCALABILITY & PROTECTION ---
CELERY_WORKER_CONCURRENCY = 4      # Limit parallel engine steps
CELERY_TASK_ACKS_LATE = True       # Re-run tasks if worker dies
CELERY_WORKER_PREFETCH_MULTIPLIER = 1 # Fair distribution for long tasks
CELERY_TASK_SOFT_TIME_LIMIT = 500  # 8.3 mins per step
CELERY_TASK_TIME_LIMIT = 600       # 10 mins hard limit

# --- EMAIL CONFIGURATION ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'ELIF Engine <noreply@elif.ai>')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    'reset-usage-every-night': {
        'task': 'discovery.reset_monthly_usage',
        'schedule': crontab(hour=0, minute=0),  # Daily at midnight
    },
}
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
LOGOUT_REDIRECT_URL = 'login'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media Files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
